[build-system]
requires = ["setuptools>=80", "setuptools-scm[simple]>=9.2"]
build-backend = "setuptools.build_meta"

[project]
name = "chaosedgesteg"
dynamic = ["version"]
requires-python = ">=3.12"
description = "Chaos-based edge adaptive steganography tool"
readme = "README.md"
keywords = ["steganography", "cli"]
authors = [{ name = "crypt0lith" }]
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Typing :: Typed",
]
dependencies = [
    "charset-normalizer",
    "mpmath",
    "numpy",
    "opencv-python",
    "pillow",
    "requests",
]

[project.urls]
Homepage = "https://github.com/crypt0lith/ChaosEdgeSteg"

[project.scripts]
chaosedgesteg = "chaosedgesteg:main"

[tool.black]
preview = true
skip-magic-trailing-comma = true
target-version = ["py312"]

[tool.isort]
profile = "black"
split_on_trailing_comma = false
combine_as_imports = true
